name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from package.json
        id: package-version
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('Assets/UnityEventTimeline/package.json', 'utf8'));
            return packageJson.version;
          result-encoding: string

      - name: Check if tag exists
        id: check-tag
        run: |
          if [ $(git tag -l "v${{ steps.package-version.outputs.result }}") ]; then
            echo "Tag v${{ steps.package-version.outputs.result }} already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a "v${{ steps.package-version.outputs.result }}" -m "Release v${{ steps.package-version.outputs.result }}"
          git push origin "v${{ steps.package-version.outputs.result }}"
